import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  Modal,
  TouchableOpacity,
  ScrollView,
  Dimensions,
  Platform,
  SafeAreaView,
} from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

const { width, height } = Dimensions.get('window');

type PrivacyModalProps = {
  visible: boolean;
  onClose: () => void;
  type: 'privacy' | 'terms';
};

const PrivacyModal = ({ visible, onClose, type }: PrivacyModalProps) => {
  const privacyContent = `Privacy Policy for Dhi Personal Assistant

Effective Date: May 2, 2025
At Dhi Personal Assistant, privacy is our core feature. Our app is designed to operate primarily offline, ensuring your data stays exclusively on your device.
1. Data Collection Policy
We are committed to privacy through technical design:
* We do not collect any personal information
* We do not require account creation or registration for our app
* We do not track your usage or interactions
* We do not use analytics or tracking tools
* We do not maintain any servers that could store your data
* We have no ability to access your conversations or prompts
2. App Store and Device Permissions
The only data collection by the app may request the following device permissions:
* Notifications access (for reminder features - processed locally)
3. Local Data Storage
All data generated through your use of Dhi Personal Assistant is stored locally on your device:
* Custom AI persona configurations
* Reminders
* Conversation history
This data remains under your control and can be deleted using your device's storage management features.
4. AI Model
Our AI model:
* Is downloaded once during app installation
* Run completely offline on your device
* Do not send data to external servers
* Do not require internet connection for operation
5. Children's Privacy
Our app can be used by children under parental supervision. Since all processing happens offline on your device, we don't collect or process any data from children (or adults). Parents are encouraged to supervise children's usage of the app.
6. Your Responsibilities
While we ensure privacy through our approach, you are responsible for:
* Maintaining your device's security
* Managing your device's backup settings
* Protecting access to your device
* Managing any data you choose to share from the app
7. Changes to This Privacy Policy
We may update this privacy policy to reflect changes in our practices or for legal reasons. We will notify you of any material changes through the app or our website.
8. Contact Us
If you have any questions about our privacy practices or this policy, please contact us at dhesha.developments@gmail.com.
`;

  const termsContent = `Terms and Conditions for Dhi Personal Assistant
Effective Date: May 2, 2025
Welcome to Dhi Personal Assistant ! These Terms and Conditions ("Terms") constitute a legally binding agreement between you and Dhi Personal Assistant regarding your use of our application and services. By accessing or using Dhi Personal Assistant, you agree to comply with and be bound by these Terms.
Acceptance of Terms
By using Dhi Personal Assistant, you confirm that you are of legal age and capacity to enter into these Terms. If you do not agree to these Terms, you must not use our app.
AI Model Limitations and Disclaimers
You acknowledge and agree that:
* The AI models in Dhi Personal Assistant may generate content that is incorrect, incomplete, misleading, or inappropriate.
* You should not rely on AI-generated content for medical, legal, financial, or other professional advice.
* The AI models may occasionally produce biased, offensive, or harmful content despite our best efforts to prevent such outputs.
* You are solely responsible for verifying any information or content generated by the AI models before acting upon it.
* Dhi Personal Assistant is not responsible for any decisions, actions, or consequences resulting from your use of AI-generated content.
* The AI models' responses are generated through probabilistic methods and may not reflect current or accurate information.
* Any code, scripts, or technical solutions generated by the AI should be thoroughly reviewed and tested before implementation.
Data and Privacy
Regarding data privacy and processing:
* When using Dhi Personal Assistant, all processing occurs on your device with no data sent to external servers
* You are responsible for the security of your device and any data you input into the app
* You are responsible for ensuring you have the right to use any content you input into the app
* You are responsible for any consequences of sharing AI-generated content with third parties
Prohibited Uses
You agree not to use Dhi Personal Assistant:
* For any unlawful purpose or to generate content that promotes illegal activities
* To generate content that is discriminatory, hateful, or promotes harm against individuals or groups
* To create misleading or fraudulent content
* To generate spam, malware, or other malicious content
* In any way that could damage, disable, or impair the app's functionality
* To attempt to reverse engineer or extract the AI model
* To generate content that infringes on intellectual property rights
* To attempt to identify or reverse engineer the training data or architecture of the AI model
* For automated or systematic extraction of content from the app
Disclaimer of Warranties
DHI  PERSONAL ASSISTANT IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED. We specifically disclaim any implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We make no warranty that:
* The app will meet your requirements or expectations
* The Dhi Personal Assistant will generate accurate, reliable, or appropriate content
* The app will be uninterrupted, timely, secure, or error-free
Limitation of Liability
TO THE MAXIMUM EXTENT PERMITTED BY LAW:
* DHI  PERSONAL ASSISTANT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES
* OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM OR RELATED TO YOUR USE OF THE APP SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE APP
* WE ARE NOT LIABLE FOR ANY ACTIONS YOU TAKE OR REFRAIN FROM TAKING BASED ON AI-GENERATED CONTENT
* WE ARE NOT LIABLE FOR ANY LOSS OF DATA, PROFIT, GOODWILL, OR BUSINESS OPPORTUNITY
* WE ARE NOT LIABLE FOR ANY INTERRUPTION OF BUSINESS OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES
* WE ARE NOT LIABLE FOR ANY ACTIONS, POLICIES, OR DATA PRACTICES OF THIRD-PARTY SERVICES
* THESE LIMITATIONS APPLY EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES
Export Control
You agree to comply with all applicable export control laws and regulations in your use of the app and its AI capabilities.
Indemnification
You agree to indemnify, defend, and hold harmless Dhi Personal Assistant and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or in any way connected with your use of the app or violation of these Terms.
Changes to Terms
We reserve the right to modify these Terms at any time. We will notify you of material changes through the app or website. Your continued use after such modifications constitutes acceptance of the updated Terms.
Governing Law and Jurisdiction
These Terms are governed by Indian law. Any disputes shall be subject to the exclusive jurisdiction of Indian courts. You agree to submit to the personal jurisdiction of such courts.
Severability
If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
Contact Us
If you have any questions about these Terms, please contact us at dhesha.developments@gmail.com.`;

  return (
    <Modal
      animationType="slide"
      transparent={true}
      visible={visible}
      onRequestClose={onClose}
    >
      <SafeAreaView style={styles.centeredView}>
        <View style={styles.modalView}>
          <View style={styles.modalHeader}>
            <Text style={styles.modalTitle}>
              {type === 'privacy' ? 'Privacy Policy' : 'Terms & Conditions'}
            </Text>
            <TouchableOpacity onPress={onClose} style={styles.closeButton}>
              <Text style={styles.closeButtonText}>✕</Text>
            </TouchableOpacity>
          </View>
          
          <ScrollView 
            style={styles.modalContent}
            showsVerticalScrollIndicator={true}
          >
            <Text style={styles.modalText}>
              {type === 'privacy' ? privacyContent : termsContent}
            </Text>
          </ScrollView>
          
          <TouchableOpacity style={styles.doneButton} onPress={onClose}>
            <Text style={styles.doneButtonText}>Done</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    </Modal>
  );
};

const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    width: width > 500 ? width * 0.7 : width * 0.9,
    height: height * 0.8,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eaeaea',
    paddingBottom: 15,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f1f1f1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  modalContent: {
    flex: 1,
    marginBottom: 15,
  },
  modalText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
    fontFamily: Platform.OS === 'ios' ? 'Helvetica Neue' : 'sans-serif',
    marginBottom: 20,
  },
  doneButton: {
    backgroundColor: COLORS.primary,
    padding: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  doneButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: FONTS.primary,
  },
});

export default PrivacyModal; 